name: flutter_clean_architecture_2022
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: 0.13.5
  get: 4.6.3
  flutter_bloc: 8.1.1
  get_it: 7.1.3
  hive: 2.2.3
  hive_flutter: 1.1.0
  cupertino_icons: 1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.3.2
  mockito: 5.3.2
  hive_generator: 2.0.0
  flutter_lints: 2.0.0


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg