// Mocks generated by Mockito 5.3.2 from annotations
// in flutter_clean_architecture_2022/test/ui/screens/play/play_vm_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_clean_architecture_2022/domain/models/result.dart'
    as _i4;
import 'package:flutter_clean_architecture_2022/domain/models/round.dart'
    as _i7;
import 'package:flutter_clean_architecture_2022/domain/usecasaes/breed_list_usecase.dart'
    as _i2;
import 'package:flutter_clean_architecture_2022/domain/usecasaes/dog_random_breed_usecase.dart'
    as _i3;
import 'package:flutter_clean_architecture_2022/domain/usecasaes/game_builder_usecase.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBreedListUsecase_0 extends _i1.SmartFake
    implements _i2.BreedListUsecase {
  _FakeBreedListUsecase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDogRandomBreedUsecase_1 extends _i1.SmartFake
    implements _i3.DogRandomBreedUsecase {
  _FakeDogRandomBreedUsecase_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResult_2<T> extends _i1.SmartFake implements _i4.Result<T> {
  _FakeResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GameCreatorUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameCreatorUsecase extends _i1.Mock
    implements _i5.GameCreatorUsecase {
  MockGameCreatorUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BreedListUsecase get breedListUsecase => (super.noSuchMethod(
        Invocation.getter(#breedListUsecase),
        returnValue: _FakeBreedListUsecase_0(
          this,
          Invocation.getter(#breedListUsecase),
        ),
      ) as _i2.BreedListUsecase);
  @override
  _i3.DogRandomBreedUsecase get dogRandomBreedUsecase => (super.noSuchMethod(
        Invocation.getter(#dogRandomBreedUsecase),
        returnValue: _FakeDogRandomBreedUsecase_1(
          this,
          Invocation.getter(#dogRandomBreedUsecase),
        ),
      ) as _i3.DogRandomBreedUsecase);
  @override
  _i6.Future<_i4.Result<List<_i7.Round>>> call({required int? numOfRounds}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#numOfRounds: numOfRounds},
        ),
        returnValue: _i6.Future<_i4.Result<List<_i7.Round>>>.value(
            _FakeResult_2<List<_i7.Round>>(
          this,
          Invocation.method(
            #call,
            [],
            {#numOfRounds: numOfRounds},
          ),
        )),
      ) as _i6.Future<_i4.Result<List<_i7.Round>>>);
}
